config:
    groups:
        /universe:
            job_agg_nodes:    [localhost]
            data_store_nodes: [localhost]
            collector_nodes:  [localhost]
    services:
        collector:
            cmdport_range: 5100-5199
            listen_port_range: 5262,
            logfile: /tmp/%(service)s_%(group)s.log
        data_store:
            cmdport_range: 5100-5199
            listen_port_range: 5200-5299
            logfile: /tmp/%(service)s_%(group)s.log
        job_agg:
            cmdport_range: 5000-5999
            listen_port_range: 5300-5999
            logfile: /tmp/%(service)s_%(jobid)s.log
    database:
        dbname: metricdb
        dbhost: localhost:27017
        user: ""
        password: ""
    global:
        local_cmd:   cd %(cwd)s; %(cmd)s >%(logfile)s 2>&1 &
        remote_cmd:  'ssh %(host)s "cd %(cwd)s; %(cmd)s >%(logfile)s 2>&1 &"'
        remote_kill: ssh %(host)s kill %(pid)d
